#!/usr/bin/env python3

import random
from datetime import datetime
random.seed(datetime.now())
import sys
import os

elements = [(1, "Hydrogene", "H", 1), (2, "Helium", "He", 4), (3, "Lithium", "Li", 7), (4, "Beryllium", "Be", 9), (5, "Bore", "B", 11), (6, "Carbone", "C", 12), (7, "Azote", "N", 14), (8, "Oxygene", "O", 16), (9, "Fluor", "F", 19), (10, "Neon", "Ne", 20)]
elements += [(11, "Sodium", "Na", 23), (12, "Magnesium", "Mg", 24), (13, "Aluminium", "Al", 27), (14, "Silicium", "Si", 28), (15, "Phosphore", "P", 31), (16, "Soufre", "S", 32), (17, "Chlore", "Cl", 35), (18, "Argon", "Ar", 40), (19, "Potassium", "K", 39), (20, "Calcium", "Ca", 40)]
elements += [(21, "Scandium", "Sc", 45), (22, "Titane", "Ti", 48), (23, "Vanadium", "V", 51), (24, "Chrome", "Cr", 52), (25, "Manganese", "Mn", 55), (26, "Fer", "Fe", 56), (27, "Cobalt", "Co", 59), (28, "Nickel", "Ni", 59), (29, "Cuivre", "Cu", 64), (30, "Zinc", "Zn", 65)]
elements += [(31, "Gallium", "Ga", 70), (32, "Germanium", "Ge", 73), (33, "Arsenic", "As", 75), (34, "Selenium", "Se", 79), (35, "Brome", "Br", 80), (36, "Krypton", "Kr", 84), (37, "Rubidium", "Rb", 85), (38, "Strontium", "Sr", 88), (39, "Yttrium", "Y", 89), (40, "Zirconium", "Zr", 91)]
elements += [(41, "Niobium", "Nb", "93"), (42, "Molybdene", "Mo", 96), (43, "Technetium", "Tc", 98), (44, "Ruthenium", "Ru", 101), (45, "Rhodium", "Rh", 103), (46, "Palladium", "Pd", 106), (47, "Argent", "Ag", 108), (48, "Cadmium", "Cd", 112), (49, "Indium", "In", 115), (50, "Etain", "Sn", 119)]
elements += [(51, "Antimoine", "Sb", 122), (52, "Tellure", "Te", 128), (53, "Iode", "I", 127), (54, "Xenon", "Xe", 131), (55, "Cesium", "Cs", 133), (56, "Baryum", "Ba", 137), (57, "Lanthane", "La", 139), (58, "Cerium", "Ce", 140), (59, "Praseodyme", "Pr", 141), (60, "Neodyme", "Nd", 144)]
elements += [(61, "Promethium", "Pm", 145), (62, "Samarium", "Sm", 150), (63, "Europium", "Eu", 152), (64, "Gadolinium", "Gd", 157), (65, "Terbium", "Tb", 159), (66, "Dysprosium", "Dy", 163), (67, "Holmium", "Ho", 165), (68, "Erbium", "Er", 167), (69, "Thulium", "Tm", 169), (70, "Ytterbium", "Yb", 173)]
elements += [(71, "Lutetium", "Lu", 175), (72, "Hafnium", "Hf", 178), (73, "Tantale", "Ta", 181), (74, "Tungstene", "W", 184), (75, "Rhenium", "Re", 186), (76, "Osmium", "Os", 190), (77, "Iridium", "Ir", 192), (78, "Platine", "Pt", 195), (79, "Or", "Au", 197), (80, "Mercure", "Hg", 201)]
elements += [(81, "Thallium", "Tl", 204), (82, "Plomb", "Pb", 207), (83, "Bismuth", "Bi", 209), (84, "Polonium", "Po", 209), (85, "Astate", "At", 210), (86, "Radon", "Rn", 222), (87, "Francium", "Fr", 223), (88, "Radium", "Ra", 226), (89, "Actinium", "Ac", 227), (90, "Thorium", "Th", 232)]
elements += [(91, "Protactinium", "Pa", 231), (92, "Uranium", "U", 238), (93, "Neptunium", "Np", 237), (94, "Plutonium", "Pu", 244), (95, "Americium", "Am", 243), (96, "Curium", "Cm", 247), (97, "Berkelium", "Bk", 247), (98, "Californium", "Cf", 251), (99, "Einsteinium", "Es", 252), (100, "Fermium", "Fm", 257)]
elements += [(101, "Mendelevium", "Md", 258), (102, "Nobelium", "No", 259), (103, "Lawrencium", "Lr", 262), (104, "Rutherfordium", "Rf", 267), (105, "Dubnium", "Db", 268), (106, "Seaborgium", "Sg", 271), (107, "Bohrium", "Bh", 272), (108, "Hassium", "Hs", 277), (109, "Meitnerium", "Mt", 276), (110, "Darmstadtium", "Ds", 281)]
elements += [(111, "Roentgenium", "Rg", 280), (112, "Copernicium", "Cn", 285), (113, "Nihonium", "Nh", 286), (114, "Flerovium", "Fl", 287), (115, "Moscovium", "Mc", 289), (116, "Livermorium", "Lv", 291), (117, "Tennesse", "Ts", 294), (118, "Oganesson", "Og", 294)]

def main():
    for e in elements:
        print([e])
#   if len(sys.argv) == 1:
#       tests = [get_random_element()]
#   elif sys.argv[1] == "all":
#       tests = elements
#       random.shuffle(tests)

#   for e in tests:
#       challenge(e)

def get_random_element():
    num = random.randint(0, len(elements) - 1)
    return elements[num]

def challenge(e):
    data_given = random.randint(0, 2)

    print(e[data_given])
    for i in range(0, 4):
        if i == data_given:
            continue
        if input() != str(e[i]):
            print("On attendait", e[i])






main()
