#!/usr/bin/env python3

import random
import os

filename = "elements.txt"
def main():
    with open(filename, "r") as fh:
        lines = import_lines(fh)

    random.shuffle(lines)

    while lines:
        os.system("clear")
        lines = check_all(lines)

def import_lines(fh, n = 99999):
    return [line.rstrip().split(" ") for line in fh.readlines()]

def check_all(array):
    fails = []
    for a in array:
        if not check(a):
            print("Fail", a)
            fails.append(a)
    return fails

def check(e):
    data_given = random.randint(0, 2)
    success = True

    print(e[data_given])
    for i in range(0, 4):
        if i == data_given:
            continue
        if input() != str(e[i]):
            print("On attendait", e[i])
            success = False
    return success

from datetime import datetime
random.seed(datetime.now())
main()
